name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.0

  # Updated intl package for date formatting
  intl: ^0.19.0

  # Replaced discontinued charts_flutter with fl_chart
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/camhub_background.jpg
    - assets/images/camhub_logo.jpg
    - assets/images/photographer1.jpg
    - assets/images/photographer2.jpg
    - assets/images/higala_logo.png
    - assets/images/higala_logo1.jpg
    - assets/images/package1.png
    - assets/images/package2.png
    - assets/images/package3.png
    - assets/images/package4.png

  # To add custom fonts to your application, add a fonts section here.
  # Example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
