name: example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.8

  # Added intl package for date formatting
  intl: ^0.17.0
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/camhub_background.jpg
    - assets/images/camhub_logo.jpg
    - assets/images/photographer1.jpg
    - assets/images/photographer2.jpg
    - assets/images/higala_logo.png
    - assets/images/package1.png
    - assets/images/package2.png
    - assets/images/package3.png
    - assets/images/package4.png

  # To add custom fonts to your application, add a fonts section here.
  # Example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
